# NumPy Assignment

In [1]:
# importing numpy and pandas

import numpy as np
import pandas as pd

# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [2]:
arr = np.arange(6)
print("The new created array is :", arr)
print("The data type of the array is :", arr.dtype)
arr

The new created array is : [0 1 2 3 4 5]
The data type of the array is : int64


array([0, 1, 2, 3, 4, 5])

# 2. Given a NumPy array 'arr', check if its data type is float64.

In [3]:
arr = np.array([1.5, 2.6, 3.7])

if arr.dtype == np.float64:
    print("The data type of the array is float64.")
else:
    print("The data type of the array is not float64.")

The data type of the array is float64.


# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [4]:
arr = np.array([1 + 1j, 2 + 2j, 3 + 3j], dtype=np.complex128)
print(arr.dtype)

complex128


# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [5]:
arr = np.array([1,2,3,4,5,6])
arr_float32 = arr.astype(np.float32)

arr_float32.dtype

dtype('float32')

# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [6]:
arr = np.array([1.123456789, 2.123456789, 3.123456789])
print(arr)
print("data type of 'arr': ",arr.dtype)

arr_float32 = arr.astype(np.float32)
print(arr_float32)
print("data type of 'arr_float32': ", arr_float32.dtype)

[1.12345679 2.12345679 3.12345679]
data type of 'arr':  float64
[1.1234568 2.1234567 3.1234567]
data type of 'arr_float32':  float32


# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [7]:
def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype

    return shape, size, dtype


arr = np.array([[1, 2, 3], [4, 5, 6]])

shape, size, dtype = array_attributes(arr)
print("Shape:", shape)
print("Size:", size)
print("Data Type:", dtype)

Shape: (2, 3)
Size: 6
Data Type: int64


# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [8]:
def array_dimension(arr):
    dimension = arr.ndim
    
    return dimension

arr = np.array([[1,2,3],[4,5,6]])

dimension = array_dimension(arr)
print("Dimensionality: ", dimension)

Dimensionality:  2


# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [9]:
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    
    return item_size, total_size

arr = np.array([[1,2,3],[4,5,6]])
item_size, total_size = item_size_info(arr)
print("Item size: ", item_size, "bytes")
print("Total size: ", total_size, "bytes")

Item size:  8 bytes
Total size:  48 bytes


# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [10]:
def array_strides(arr):
    strides = arr.strides
    
    return strides

arr = np.array([[1,2,3],[4,5,6]])

strides = array_strides(arr)
print("Strides: ", strides)

Strides:  (24, 8)


# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [11]:
def shape_stride_relationship(arr):
    shape = arr.shape
    strides = arr.strides
    
    return shape, strides

arr = np.array([[1,2,3],[4,5,6]])

shape, strides = shape_stride_relationship(arr)
print("Shape: ", shape)
print("Strides: ", strides)

Shape:  (2, 3)
Strides:  (24, 8)


# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

In [12]:
def create_zeros_array(n):
    arr = np.zeros(n)
    
    return arr

n = 5

arr = create_zeros_array(n)
print("Array of zeros with ", n, "elements: ")
arr

Array of zeros with  5 elements: 


array([0., 0., 0., 0., 0.])

# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

In [13]:
def create_ones_matrix(rows, cols):
    
    return np.ones((rows, cols))


rows = 3
cols = 4

matrix = create_ones_matrix(rows, cols)
print("Matrix of ones with", rows, "rows and", cols, "columns:")
print(matrix)

Matrix of ones with 3 rows and 4 columns:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

In [14]:
def generate_range_array(start, stop, step):
    
    return np.arange(start, stop, step)

start = 1
stop = 20
step = 2

arr = generate_range_array(start, stop, step)
print("Array with range from", start, "to", stop, "with step", step, ":")
print(arr)

Array with range from 1 to 20 with step 2 :
[ 1  3  5  7  9 11 13 15 17 19]


# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

In [15]:
def generate_linear_space(start, stop, num):
    
    return np.linspace(start, stop, num)

start = 0.1
stop = 0.99
num = 5

arr = generate_linear_space(start, stop, num)
print("Array with", num, "equally spaced values between", start, "and", stop, ":")
print(arr)

Array with 5 equally spaced values between 0.1 and 0.99 :
[0.1    0.3225 0.545  0.7675 0.99  ]


# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

In [16]:
def create_identity_matrix(n):
    return np.eye(n)

n = 3

matrix = create_identity_matrix(n)
print("Identity matrix of size", n, "x", n, ":")
print(matrix)

Identity matrix of size 3 x 3 :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 16. Write a function that takes a Python list and converts it into a NumPy array.

In [17]:
def list_to_numpy_array(lst):
    
    return np.array(lst)

lst = [1,2,3,4,5]

arr = list_to_numpy_array(lst)
print("NumPy array from python list:")
arr

NumPy array from python list:


array([1, 2, 3, 4, 5])

# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data

In [18]:
# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5])
print("Original array:", original_array)

# Create a new array object with the same data using numpy.view
view_array = original_array.view()
print("View array:", view_array)

# Modify the original array
original_array[0] = 10
print("Modified original array:", original_array)

# The view array is also modified because it shares the same data
print("View array after modifying original array:", view_array)

Original array: [1 2 3 4 5]
View array: [1 2 3 4 5]
Modified original array: [10  2  3  4  5]
View array after modifying original array: [10  2  3  4  5]


# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [19]:
def concatenate_arrays(arr1, arr2, axis = 0):
    
    return np.concatenate((arr1, arr2), axis = axis)

arr1 = np.array([[1,2,],[3,4]])
arr2 = np.array([[5,6],[7,8]])

print("Concatenated array along axis 0:")
print(concatenate_arrays(arr1, arr2, axis = 0))

print("\nConcatenated array along axis 1:")
print(concatenate_arrays(arr1, arr2, axis = 1))

Concatenated array along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated array along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

In [20]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[4,5],[6,7]])

print("Array 1 shape:", arr1.shape)
print("Array 2 shape:", arr2.shape)

array = np.concatenate((arr1, arr2), axis = 1)
print(array)

Array 1 shape: (2, 3)
Array 2 shape: (2, 2)
[[1 2 3 4 5]
 [4 5 6 6 7]]


# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [21]:
def vstack_arrays(arr):
    
    return np.vstack(arr)

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

arrays = [array1, array2]
stacked_array = vstack_arrays(arrays)

print(stacked_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [22]:
def create_range_array(start, stop, step):
    
    return np.arange(start, stop + 1, step)

array = create_range_array(0, 9, 2)
print(array)

[0 2 4 6 8]


# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [23]:
import numpy as np

def generate_evenly_spaced_array(start, stop, num_elements):
    
    return np.linspace(start, stop, num_elements)

array = generate_evenly_spaced_array(0, 1, 10)
print(array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [24]:
import numpy as np

def generate_log_space(start=1, stop=1000, num=5):
    
    return np.logspace(np.log10(start), np.log10(stop), num)

values = generate_log_space()
print(values)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [25]:
data = np.random.randint(1, 101, (5, 3))

df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])

df

Column1  Column2  Column3
0       61       80       98
1       99       48       13
2       25       25       42
3       81       32       50
4       36       84       15

# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [26]:
import pandas as pd
import numpy as np

def replace_negative_with_zero(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df


df = pd.DataFrame({
    'A': [-1, 2, -3, 4, 5],
    'B': [6, 7, 8, 9, 10]
})

print("Original DataFrame:")
print(df)

df = replace_negative_with_zero(df, 'A')

print("\nDataFrame after replacing negative values with zeros:")
print(df)

Original DataFrame:
   A   B
0 -1   6
1  2   7
2 -3   8
3  4   9
4  5  10

DataFrame after replacing negative values with zeros:
   A   B
0  0   6
1  2   7
2  0   8
3  4   9
4  5  10


# 26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

In [27]:
arr = np.array([10, 20, 30, 40, 50])

third_element = arr[2]

print("The 3rd element is:", third_element)

The 3rd element is: 30


# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],

                   [4, 5, 6],

                   [7, 8, 9]])

In [28]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)

The element at index (1, 2) is: 6


# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])

In [29]:
arr = np.array([3, 8, 2, 10, 5, 7])

greater_than_5 = arr[arr > 5]

print("Elements greater than 5:", greater_than_5)

Elements greater than 5: [ 8 10  7]


# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sliced_arr = arr[2:6]

print("Elements from index 2 to 5 (inclusive):", sliced_arr)

Elements from index 2 to 5 (inclusive): [3 4 5 6]


# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array
arr_2d = np.array([[1, 2, 3],

                   [4, 5, 6],

                   [7, 8, 9]])

In [31]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sliced_arr = arr_2d[0:2, 1:3]

print("Sub-array [[2, 3], [5, 6]]:", sliced_arr)

Sub-array [[2, 3], [5, 6]]: [[2 3]
 [5 6]]


# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [32]:
def extract_elements(arr, indices):
    return arr[tuple(indices.T)]

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 1], [1, 2], [2, 0]])

extracted_elements = extract_elements(arr, indices)
print("Extracted elements:", extracted_elements)

Extracted elements: [2 6 7]


# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [33]:
def filter_elements(arr, threshold):
    return arr[arr > threshold]

# Example usage:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
threshold = 5

filtered_elements = filter_elements(arr, threshold)
print("Filtered elements:", filtered_elements)

Filtered elements: [6 7 8 9]


# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [34]:
def extract_elements(arr, row_indices, col_indices, depth_indices):
    return arr[row_indices, col_indices, depth_indices]

# Example usage:
arr = np.random.rand(3, 4, 5)  # Create a 3D array
row_indices = np.array([0, 1, 2, 0, 1])
col_indices = np.array([1, 2, 3, 0, 1])
depth_indices = np.array([0, 1, 2, 3, 4])

extracted_elements = extract_elements(arr, row_indices, col_indices, depth_indices)
print("Extracted elements:", extracted_elements)

Extracted elements: [0.46001935 0.7718399  0.19082225 0.37402364 0.30311151]


# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [35]:
def filter_elements(arr, cond1, cond2):
    mask = (cond1(arr)) & (cond2(arr))
    return arr[mask]

# Example usage:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

def cond1(x):
    return x % 2 == 0  # Condition 1: even numbers

def cond2(x):
    return x > 4  # Condition 2: greater than 4

filtered_elements = filter_elements(arr, cond1, cond2)
print("Filtered elements:", filtered_elements)

Filtered elements: [6 8]


# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [36]:
def extract_elements(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2, 0, 1])
col_indices = np.array([1, 2, 0, 0, 1])

extracted_elements = extract_elements(arr, row_indices, col_indices)
print("Extracted elements:", extracted_elements)

Extracted elements: [2 6 7 1 5]


# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [37]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Add a scalar value of 5 to each element using broadcasting
result = arr + 5

print("Original array:")
print(arr)
print("Result array:")
print(result)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Result array:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [38]:
arr1 = np.array([[1], [2], [3]])

arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Multiply each row of arr2 by the corresponding element in arr1 using broadcasting
result = arr1 * arr2

print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)
print("Result array:")
print(result)

Array 1:
[[1]
 [2]
 [3]]
Array 2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Result array:
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [39]:
arr1 = np.array([[1], [2], [3], [4]])

arr2 = np.array([[10, 10, 10], [20, 20, 20], [30, 30, 30], [40, 40, 40]])

# Add arr1 to each row of arr2 using broadcasting
result = arr2 + arr1

print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)
print("Result array:")
print(result)

Array 1:
[[1]
 [2]
 [3]
 [4]]
Array 2:
[[10 10 10]
 [20 20 20]
 [30 30 30]
 [40 40 40]]
Result array:
[[11 11 11]
 [22 22 22]
 [33 33 33]
 [44 44 44]]


# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [40]:
arr1 = np.array([[1], [2], [3]])

arr2 = np.array([[4, 5, 6]])

# Add arr1 and arr2 using broadcasting
result = arr1 + arr2

print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)
print("Result array:")
print(result)

Array 1:
[[1]
 [2]
 [3]]
Array 2:
[[4 5 6]]
Result array:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [41]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

arr2 = np.array([[7, 8], [9, 10]])

arr2 = arr2[:, :, np.newaxis]

# Perform multiplication using broadcasting
result = arr1 * arr2

print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)
print("Result array:")
print(result)

Array 1:
[[1 2 3]
 [4 5 6]]
Array 2:
[[[ 7]
  [ 8]]

 [[ 9]
  [10]]]
Result array:
[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


# 41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

column_mean = np.mean(arr, axis=0)

print("Original array:")
print(arr)
print("Column-wise mean:")
print(column_mean)

Original array:
[[1 2 3]
 [4 5 6]]
Column-wise mean:
[2.5 3.5 4.5]


# 42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

row_max = np.max(arr, axis=1)

print("Original array:")
print(arr)
print("Maximum value in each row:")
print(row_max)

Original array:
[[1 2 3]
 [4 5 6]]
Maximum value in each row:
[3 6]


# 43. For the given array, find indices of maximum value in each column
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [44]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

column_max_indices = np.argmax(arr, axis=0)

print("Original array:")
print(arr)
print("Indices of maximum value in each column:")
print(column_max_indices)

Original array:
[[1 2 3]
 [4 5 6]]
Indices of maximum value in each column:
[1 1 1]


# 44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

def moving_sum(a, window_size):
    return [sum(a[i:i+window_size]) for i in range(len(a) - window_size + 1)]

# Apply the custom function to calculate moving sum along rows
window_size = 2
moving_sum_along_rows = [moving_sum(row, window_size) for row in arr]

print("Original array:")
print(arr)
print("Moving sum along rows:")
print(moving_sum_along_rows)

Original array:
[[1 2 3]
 [4 5 6]]
Moving sum along rows:
[[3, 5], [9, 11]]


# 45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])

In [46]:
arr = np.array([[2, 4, 6], [3, 5, 7]])

even_columns = np.all(arr % 2 == 0, axis=0)

print("Original array:")
print(arr)
print("Columns with all even elements:")
print(even_columns)

Original array:
[[2 4 6]
 [3 5 7]]
Columns with all even elements:
[False False False]


# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])

In [47]:
original_array = np.array([1, 2, 3, 4, 5, 6])

m = 2
n = 3

reshaped_matrix = original_array.reshape(m, n)

print("Original array:")
print(original_array)
print("Reshaped matrix:")
print(reshaped_matrix)

Original array:
[1 2 3 4 5 6]
Reshaped matrix:
[[1 2 3]
 [4 5 6]]


47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [48]:
def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

flattened_array = flatten_matrix(input_matrix)

print("Input matrix:")
print(input_matrix)
print("Flattened array:")
print(flattened_array)

Input matrix:
[[1 2 3]
 [4 5 6]]
Flattened array:
[1 2 3 4 5 6]


# 48. Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])

array2 = np.array([[5, 6], [7, 8]])

In [49]:
def concatenate_arrays(array1, array2, axis):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

concatenated_array_axis0 = concatenate_arrays(array1, array2, axis=0)

concatenated_array_axis1 = concatenate_arrays(array1, array2, axis=1)

print("Array 1:")
print(array1)
print("Array 2:")
print(array2)
print("Concatenated array along axis 0:")
print(concatenated_array_axis0)
print("Concatenated array along axis 1:")
print(concatenated_array_axis1)

Array 1:
[[1 2]
 [3 4]]
Array 2:
[[5 6]
 [7 8]]
Concatenated array along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated array along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [50]:
def split_array(array, num_subarrays, axis):
    return np.split(array, num_subarrays, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

subarrays_axis0 = split_array(original_array, 3, axis=0)

subarrays_axis1 = split_array(original_array, 3, axis=1)

print("Original array:")
print(original_array)
print("Sub-arrays along axis 0:")
for i, subarray in enumerate(subarrays_axis0):
    print(f"Sub-array {i+1}:")
    print(subarray)
print("Sub-arrays along axis 1:")
for i, subarray in enumerate(subarrays_axis1):
    print(f"Sub-array {i+1}:")
    print(subarray)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sub-arrays along axis 0:
Sub-array 1:
[[1 2 3]]
Sub-array 2:
[[4 5 6]]
Sub-array 3:
[[7 8 9]]
Sub-arrays along axis 1:
Sub-array 1:
[[1]
 [4]
 [7]]
Sub-array 2:
[[2]
 [5]
 [8]]
Sub-array 3:
[[3]
 [6]
 [9]]


# 50. Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])

indices_to_insert = [2, 4]

values_to_insert = [10, 11]

indices_to_delete = [1, 3]

In [51]:
def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    # Convert the original array to a list for easier manipulation
    array_list = original_array.tolist()
    
    # Insert new elements at specified indices
    for index, value in zip(indices_to_insert, values_to_insert):
        array_list.insert(index, value)
    
    # Delete elements at specified indices
    for index in sorted(indices_to_delete, reverse=True):
        del array_list[index]
    
    # Convert the list back to a numpy array
    modified_array = np.array(array_list)
    
    return modified_array

# Create a 1D array
original_array = np.array([1, 2, 3, 4, 5])

# Specify the indices and values to insert
indices_to_insert = [2, 4]
values_to_insert = [10, 11]

# Specify the indices to delete
indices_to_delete = [1, 3]

# Insert and delete elements
modified_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Original array:")
print(original_array)
print("Modified array:")
print(modified_array)

Original array:
[1 2 3 4 5]
Modified array:
[ 1 10 11  4  5]


# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [52]:
# Create a NumPy array arr1 with random integers
arr1 = np.random.randint(1, 100, 10)
print("Array 1 (arr1):")
print(arr1)

# Create a NumPy array arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)
print("Array 2 (arr2):")
print(arr2)

# Perform element-wise addition between arr1 and arr2
result = arr1 + arr2
print("Element-wise addition result:")
print(result)

Array 1 (arr1):
[ 2 59 68 59 49 25 27 67 16 98]
Array 2 (arr2):
[ 1  2  3  4  5  6  7  8  9 10]
Element-wise addition result:
[  3  61  71  63  54  31  34  75  25 108]


# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [53]:
# Generate a NumPy array arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)
print("Array 1 (arr1):")
print(arr1)

# Generate a NumPy array arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)
print("Array 2 (arr2):")
print(arr2)

# Subtract arr2 from arr1 element-wise
result = arr1 - arr2
print("Element-wise subtraction result:")
print(result)

Array 1 (arr1):
[10  9  8  7  6  5  4  3  2  1]
Array 2 (arr2):
[ 1  2  3  4  5  6  7  8  9 10]
Element-wise subtraction result:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

In [54]:
# Create a NumPy array arr1 with random integers
arr1 = np.random.randint(1, 10, 5)
print("Array 1 (arr1):")
print(arr1)

# Create a NumPy array arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)
print("Array 2 (arr2):")
print(arr2)

# Perform element-wise multiplication between arr1 and arr2
result = arr1 * arr2
print("Element-wise multiplication result:")
print(result)

Array 1 (arr1):
[5 8 6 7 3]
Array 2 (arr2):
[1 2 3 4 5]
Element-wise multiplication result:
[ 5 16 18 28 15]


# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [55]:
# Generate a NumPy array arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)
print("Array 1 (arr1):")
print(arr1)

# Generate a NumPy array arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)
print("Array 2 (arr2):")
print(arr2)

# Perform element-wise division of arr1 by arr2
result = arr1 / arr2
print("Element-wise division result:")
print(result)

Array 1 (arr1):
[ 2  4  6  8 10]
Array 2 (arr2):
[1 2 3 4 5]
Element-wise division result:
[2. 2. 2. 2. 2.]


# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [56]:
# Create a NumPy array arr1 with integers from 1 to 5
arr1 = np.arange(1, 6)
print("Array 1 (arr1):")
print(arr1)

# Create a NumPy array arr2 with the same numbers reversed
arr2 = np.arange(5, 0, -1)
print("Array 2 (arr2):")
print(arr2)

# Calculate the exponentiation of arr1 raised to the power of arr2 element-wise
result = arr1 ** arr2
print("Element-wise exponentiation result:")
print(result)

Array 1 (arr1):
[1 2 3 4 5]
Array 2 (arr2):
[5 4 3 2 1]
Element-wise exponentiation result:
[ 1 16 27 16  5]


# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [57]:
def count_substring(arr, substring):
    return np.sum(np.char.find(arr, substring)!= -1)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

count = count_substring(arr, substring)
print(f"The substring '{substring}' occurs {count} times in the array.")

The substring 'hello' occurs 3 times in the array.


# 57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [58]:
def extract_uppercase(arr):
    return np.array([''.join(filter(str.isupper, word)) for word in arr])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
result = extract_uppercase(arr)
print(result)

['H' 'W' 'OAI' 'GPT']


# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [59]:
def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old = 'apple'
new = 'mango'

result = replace_substring(arr, old, new)
print(result)

['mango' 'banana' 'grape' 'pinemango']


# 59. Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [60]:
def concatenate_strings(arr1, arr2):
    return np.core.defchararray.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concatenate_strings(arr1, arr2)
print(result)

['HelloOpen' 'WorldAI']


# 60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [61]:
def longest_string_length(arr):
    return np.max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

result = longest_string_length(arr)
print(result)

9


# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [62]:
# Create a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, 100)

# Compute the mean
mean = np.mean(dataset)
print("Mean:", mean)

# Compute the median
median = np.median(dataset)
print("Median:", median)

# Compute the variance
variance = np.var(dataset)
print("Variance:", variance)

# Compute the standard deviation
std_dev = np.std(dataset)
print("Standard Deviation:", std_dev)

Mean: 480.74
Median: 479.0
Variance: 85866.83240000001
Standard Deviation: 293.0304291366342


# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [63]:
# Generate an array of 50 random numbers between 1 and 100
dataset = np.random.randint(1, 101, 50)

# Sort the dataset in ascending order
dataset.sort()

# Find the 25th percentile (Q1)
q1 = np.percentile(dataset, 25)
print("25th Percentile (Q1):", q1)

# Find the 75th percentile (Q3)
q3 = np.percentile(dataset, 75)
print("75th Percentile (Q3):", q3)

25th Percentile (Q1): 25.25
75th Percentile (Q3): 74.75


# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [64]:
# Create two arrays representing two sets of variables
array1 = np.array([23, 11, 18, 25, 9, 17, 22, 20, 15, 24])
array2 = np.array([12, 15, 8, 21, 10, 19, 13, 16, 11, 14])

# Compute the correlation coefficient between the two arrays
correlation_coefficient = np.corrcoef(array1, array2)[0, 1]

print("Correlation Coefficient:", correlation_coefficient)

Correlation Coefficient: 0.3671242883813547


# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [65]:
# Create two matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])

# Perform matrix multiplication using NumPy's dot function
result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)
print("Result of Matrix Multiplication:")
print(result)

Matrix 1:
[[1 2 3]
 [4 5 6]]
Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]
Result of Matrix Multiplication:
[[ 58  64]
 [139 154]]


# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [66]:
# Create an array of 50 integers between 10 and 1000
array = np.random.randint(10, 1001, 50)

# Calculate the 10th, 50th (median), and 90th percentiles
percentile_10 = np.percentile(array, 10)
percentile_50 = np.percentile(array, 50)
percentile_90 = np.percentile(array, 90)

# Calculate the first and third quartiles (25th and 75th percentiles)
quartile_1 = np.percentile(array, 25)
quartile_3 = np.percentile(array, 75)

print("Original Array:")
print(array)
print("\nPercentiles and Quartiles:")
print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (25th Percentile):", quartile_1)
print("Third Quartile (75th Percentile):", quartile_3)

Original Array:
[341 269 809  56 125 469  28 493 449 104 394 946  25  59  94 105 664  23
 239  50 128 932 401 537 543 982 722 478 957 104 382 258 118 274 345 334
  87 380 737 233 860 354 145 933  60 462 455 178 411 856]

Percentiles and Quartiles:
10th Percentile: 58.7
50th Percentile (Median): 349.5
90th Percentile: 867.2
First Quartile (25th Percentile): 119.75
Third Quartile (75th Percentile): 526.0


# 66. Create a NumPy array of integers and find the index of a specific element.

In [67]:
# Create a NumPy array of integers
array = np.array([12, 25, 37, 48, 59, 61, 72, 83, 94, 105])

# Specify the element to find
target_element = 61

# Find the index of the target element
index = np.where(array == target_element)[0][0]

print("Original Array:")
print(array)
print("\nIndex of", target_element, ":", index)

Original Array:
[ 12  25  37  48  59  61  72  83  94 105]

Index of 61 : 5


# 67. Generate a random NumPy array and sort it in ascending order.

In [68]:
# Generate a random NumPy array
array = np.random.randint(0, 100, 10)

print("Original Array:")
print(array)

# Sort the array in ascending order
sorted_array = np.sort(array)

print("\nSorted Array:")
print(sorted_array)

Original Array:
[62 20 91  2 26 64 64 66 47 95]

Sorted Array:
[ 2 20 26 47 62 64 64 66 91 95]


# 68. Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])

In [69]:
# Given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

print("Original Array:")
print(arr)

# Filter elements greater than 20
filtered_array = arr[arr > 20]

print("\nFiltered Array (elements > 20):")
print(filtered_array)

Original Array:
[12 25  6 42  8 30]

Filtered Array (elements > 20):
[25 42 30]


# 69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])

In [70]:
# Given NumPy array
arr = np.array([1, 5, 8, 12, 15])

print("Original Array:")
print(arr)

# Filter elements divisible by 3
filtered_array = arr[arr % 3 == 0]

print("\nFiltered Array (elements divisible by 3):")
print(filtered_array)

Original Array:
[ 1  5  8 12 15]

Filtered Array (elements divisible by 3):
[12 15]


# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

In [71]:
# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

print("Original Array:")
print(arr)

# Filter elements ≥ 20 and ≤ 40
filtered_array = arr[(arr >= 20) & (arr <= 40)]

print("\nFiltered Array (elements ≥ 20 and ≤ 40):")
print(filtered_array)

Original Array:
[10 20 30 40 50]

Filtered Array (elements ≥ 20 and ≤ 40):
[20 30 40]


# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])

In [72]:
# Given NumPy array
arr = np.array([1, 2, 3])

print("Original Array:")
print(arr)

# Check byte order using dtype.byteorder
byte_order = arr.dtype.byteorder

print("\nByte Order:")
print(byte_order)

Original Array:
[1 2 3]

Byte Order:
=


# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [73]:
# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

print("Original Array:")
print(arr)

print("\nOriginal Byte Order:")
print(arr.dtype.byteorder)

# Perform byte swapping in place using byteswap()
arr.byteswap(inplace=True)

print("\nArray after Byte Swapping:")
print(arr)

print("\nByte Order after Byte Swapping:")
print(arr.dtype.byteorder)

Original Array:
[1 2 3]

Original Byte Order:
=

Array after Byte Swapping:
[16777216 33554432 50331648]

Byte Order after Byte Swapping:
=


# 73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [74]:
# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

print("Original Array:")
print(arr)

print("\nOriginal Byte Order:")
print(arr.dtype.byteorder)

# Swap byte order without modifying the original array using newbyteorder()
swapped_arr = arr.newbyteorder()

print("\nSwapped Array:")
print(swapped_arr)

print("\nByte Order of Swapped Array:")
print(swapped_arr.dtype.byteorder)

Original Array:
[1 2 3]

Original Byte Order:
=

Swapped Array:
[16777216 33554432 50331648]

Byte Order of Swapped Array:
>


# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [75]:
arr = np.array([1, 2, 3], dtype=np.int32)

print("Original Array:")
print(arr)

print("\nOriginal Byte Order:")
print(arr.dtype.byteorder)

# Get the system endianness
system_endianness = '<' if np.little_endian else '>'

print(f"\nSystem Endianness: {system_endianness}")

# Swap byte order conditionally based on system endianness using newbyteorder()
if arr.dtype.byteorder != system_endianness:
    swapped_arr = arr.newbyteorder()
    print("\nSwapped Array:")
    print(swapped_arr)
    print("\nByte Order of Swapped Array:")
    print(swapped_arr.dtype.byteorder)
else:
    print("\nNo need to swap byte order, as it matches the system endianness.")
    swapped_arr = arr
    print("Swapped Array:")
    print(swapped_arr)
    print("Byte Order of Swapped Array:")
    print(swapped_arr.dtype.byteorder)

Original Array:
[1 2 3]

Original Byte Order:
=

System Endianness: <

Swapped Array:
[16777216 33554432 50331648]

Byte Order of Swapped Array:
>


# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [76]:
arr = np.array([1, 2, 3], dtype=np.int32)

print("Original Array:")
print(arr)

print("\nOriginal Byte Order:")
print(arr.dtype.byteorder)

# Check if byte swapping is necessary for the current system
if arr.dtype.byteorder == '=':
    print("\nNo byte swapping is necessary, as the array's byte order matches the system's native byte order.")
else:
    print("\nByte swapping is necessary, as the array's byte order does not match the system's native byte order.")

Original Array:
[1 2 3]

Original Byte Order:
=

No byte swapping is necessary, as the array's byte order matches the system's native byte order.


# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [77]:
# Create a NumPy array arr1 with values from 1 to 10
arr1 = np.arange(1, 11)
print("Original Array arr1:")
print(arr1)

# Create a copy of arr1 named copy_arr
copy_arr = arr1.copy()
print("\nCopy of arr1 (copy_arr):")
print(copy_arr)

# Modify an element in copy_arr
copy_arr[0] = 100
print("\nModified copy_arr:")
print(copy_arr)

# Check if modifying copy_arr affects arr1
print("\nOriginal Array arr1 after modifying copy_arr:")
print(arr1)

Original Array arr1:
[ 1  2  3  4  5  6  7  8  9 10]

Copy of arr1 (copy_arr):
[ 1  2  3  4  5  6  7  8  9 10]

Modified copy_arr:
[100   2   3   4   5   6   7   8   9  10]

Original Array arr1 after modifying copy_arr:
[ 1  2  3  4  5  6  7  8  9 10]


# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [78]:
# Create a 2D NumPy array matrix of shape (3, 3) with random integers
matrix = np.random.randint(0, 10, size=(3, 3))
print("Original Matrix:")
print(matrix)

# Extract a slice view_slice from the matrix
view_slice = matrix[1:, 1:]
print("\nSlice View (view_slice):")
print(view_slice)

# Modify an element in view_slice
view_slice[0, 0] = 100
print("\nModified Slice View (view_slice):")
print(view_slice)

# Observe if modifying view_slice changes the original matrix
print("\nOriginal Matrix after modifying view_slice:")
print(matrix)

Original Matrix:
[[2 6 7]
 [5 6 0]
 [9 5 6]]

Slice View (view_slice):
[[6 0]
 [5 6]]

Modified Slice View (view_slice):
[[100   0]
 [  5   6]]

Original Matrix after modifying view_slice:
[[  2   6   7]
 [  5 100   0]
 [  9   5   6]]


# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [79]:
# Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape((4, 3))
print("Original Array array_a:")
print(array_a)

# Extract a slice view_b from array_a
view_b = array_a[1:, 1:]
print("\nSlice View (view_b):")
print(view_b)

# Broadcast the addition of 5 to view_b
view_b += 5
print("\nModified Slice View (view_b) after adding 5:")
print(view_b)

# Check if modifying view_b alters the original array_a
print("\nOriginal Array array_a after modifying view_b:")
print(array_a)

Original Array array_a:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Slice View (view_b):
[[ 5  6]
 [ 8  9]
 [11 12]]

Modified Slice View (view_b) after adding 5:
[[10 11]
 [13 14]
 [16 17]]

Original Array array_a after modifying view_b:
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 16 17]]


# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

In [80]:
# Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape((2, 4))
print("Original Array orig_array:")
print(orig_array)

# Create a reshaped view reshaped_view of shape (4, 2) from orig_array
reshaped_view = orig_array.reshape((4, 2))
print("\nReshaped View reshaped_view:")
print(reshaped_view)

# Modify an element in reshaped_view
reshaped_view[1, 0] = 100
print("\nModified Reshaped View reshaped_view:")
print(reshaped_view)

# Check if modifying reshaped_view reflects changes in the original orig_array
print("\nOriginal Array orig_array after modifying reshaped_view:")
print(orig_array)

Original Array orig_array:
[[1 2 3 4]
 [5 6 7 8]]

Reshaped View reshaped_view:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified Reshaped View reshaped_view:
[[  1   2]
 [100   4]
 [  5   6]
 [  7   8]]

Original Array orig_array after modifying reshaped_view:
[[  1   2 100   4]
 [  5   6   7   8]]


# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [81]:
# Create a NumPy array data of shape (3, 4) with random integers
np.random.seed(0)  # For reproducibility
data = np.random.randint(0, 10, size=(3, 4))
print("Original Array data:")
print(data)

# Extract a copy data_copy of elements greater than 5
data_copy = data[data > 5].copy()
print("\nCopy of elements greater than 5 (data_copy):")
print(data_copy)

# Modify an element in data_copy
data_copy[0] = 100
print("\nModified Copy data_copy:")
print(data_copy)

# Verify if modifying data_copy affects the original data
print("\nOriginal Array data after modifying data_copy:")
print(data)

Original Array data:
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]

Copy of elements greater than 5 (data_copy):
[7 9 7 6]

Modified Copy data_copy:
[100   9   7   6]

Original Array data after modifying data_copy:
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [82]:
# Create two matrices A and B of identical shape containing integers
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# Perform addition operation between A and B
add_result = A + B
print("\nAddition Result (A + B):")
print(add_result)

# Perform subtraction operation between A and B
sub_result = A - B
print("\nSubtraction Result (A - B):")
print(sub_result)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[10 11 12]
 [13 14 15]
 [16 17 18]]

Addition Result (A + B):
[[11 13 15]
 [17 19 21]
 [23 25 27]]

Subtraction Result (A - B):
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [83]:
# Generate two matrices C (3x2) and D (2x4)
C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])

print("Matrix C:")
print(C)
print("\nMatrix D:")
print(D)

# Perform matrix multiplication between C and D
mul_result = np.matmul(C, D)
print("\nMatrix Multiplication Result (C @ D):")
print(mul_result)

Matrix C:
[[1 2]
 [3 4]
 [5 6]]

Matrix D:
[[ 7  8  9 10]
 [11 12 13 14]]

Matrix Multiplication Result (C @ D):
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


# 83. Create a matrix `E` and find its transpose.

In [84]:
# Create a matrix E
E = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Matrix E:")
print(E)

# Find the transpose of matrix E
E_transpose = E.transpose()
print("\nTranspose of Matrix E:")
print(E_transpose)

Matrix E:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of Matrix E:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# 84. Generate a square matrix `F` and compute its determinant.

In [85]:
# Generate a square matrix F
F = np.array([[1, 2, 3], [0, 4, 5], [2, 3, 1]])

print("Matrix F:")
print(F)

# Compute the determinant of matrix F
det_F = np.linalg.det(F)
print("\nDeterminant of Matrix F:")
print(det_F)

Matrix F:
[[1 2 3]
 [0 4 5]
 [2 3 1]]

Determinant of Matrix F:
-14.999999999999993


# 85. Create a square matrix `G` and find its inverse.

In [86]:
# Create a square matrix G
G = np.array([[1, 2], [3, 4]])

print("Matrix G:")
print(G)

# Find the inverse of matrix G
G_inverse = np.linalg.inv(G)
print("\nInverse of Matrix G:")
print(G_inverse)

Matrix G:
[[1 2]
 [3 4]]

Inverse of Matrix G:
[[-2.   1. ]
 [ 1.5 -0.5]]
